# .github/workflows/convert-to-pdf.yml

name: Labs to PDF
# This workflow is triggered on pushes to the repository or manually.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /labs directory
    paths:
      - "labs/*/*.md"
      - "labs/*/images/**"
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      # Convert each lab to PDF
      - name: Convert labs to PDF
        run: |
          mkdir -p pdfs
          
          # Create a simple CSS file for styling
          cat > style.css << 'EOF'
          body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            max-width: 800px; 
            margin: 40px auto; 
            padding: 20px;
            line-height: 1.6;
          } 
          img { 
            max-width: 100%; 
            height: auto; 
            display: block;
            margin: 20px 0;
          }
          code {
            background-color: #f4f4f4;
            padding: 2px 4px;
            border-radius: 3px;
          }
          pre {
            background-color: #f4f4f4;
            padding: 10px;
            border-radius: 5px;
            overflow-x: auto;
          }
          h1, h2, h3, h4, h5, h6 {
            color: #333;
            margin-top: 30px;
          }
          EOF

          # Process each lab directory individually
          for lab_dir in labs/*/; do
            if [ -f "${lab_dir}README.md" ]; then
              lab_name=$(basename "$lab_dir")
              echo "Converting $lab_name to PDF..."
              
              # Convert using pandoc with proper options
              pandoc "${lab_dir}README.md" \
                --pdf-engine=wkhtmltopdf \
                --css=style.css \
                --standalone \
                --self-contained \
                -V margin-top=0.75in \
                -V margin-bottom=0.75in \
                -V margin-left=0.75in \
                -V margin-right=0.75in \
                -o "pdfs/${lab_name}.pdf" \
                2>&1 || echo "Warning: Failed to convert $lab_name"
            fi
          done

          echo "Generated PDFs:"
          ls -la pdfs/ || echo "No PDFs directory found"
          
          # Show what we actually have
          echo "Contents of current directory:"
          ls -la

      - uses: actions/upload-artifact@v4
        with:
          name: lab-pdfs
          path: pdfs
