# .github/workflows/convert-to-pdf.yml

name: Labs to PDF
# This workflow is triggered on pushes to the repository or manually.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /labs directory
    paths:
      - "labs/*/*.md"
      - "labs/*/images/**"
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      # Debug and convert labs to PDF
      - name: Debug lab structure and convert to PDF
        run: |
          echo "=== DEBUGGING LAB STRUCTURE ==="
          echo "Current directory:"
          pwd
          ls -la
          
          echo ""
          echo "Labs directory:"
          ls -la labs/
          
          echo ""
          echo "Looking for README.md files:"
          find labs -name "README.md" -type f
          
          echo ""
          echo "=== STARTING PDF CONVERSION ==="
          mkdir -p pdfs
          
          # Simple conversion without complex CSS first
          echo "Processing lab directories..."
          for lab_dir in labs/*/; do
            echo "Checking directory: $lab_dir"
            if [ -d "$lab_dir" ]; then
              if [ -f "${lab_dir}README.md" ]; then
                lab_name=$(basename "$lab_dir")
                echo "✓ Found README.md in $lab_name"
                
                # Try simple pandoc conversion first
                echo "Converting $lab_name to PDF..."
                if pandoc "${lab_dir}README.md" -o "pdfs/${lab_name}.pdf" --pdf-engine=wkhtmltopdf 2>&1; then
                  echo "✓ Successfully converted $lab_name"
                else
                  echo "✗ Failed to convert $lab_name"
                  # Try alternative conversion
                  echo "Trying alternative method for $lab_name..."
                  pandoc "${lab_dir}README.md" -o "pdfs/${lab_name}.html" 2>&1 || echo "HTML conversion also failed"
                fi
              else
                echo "✗ No README.md found in $lab_dir"
              fi
            fi
          done
          
          echo ""
          echo "=== FINAL RESULTS ==="
          echo "Contents of pdfs directory:"
          if [ -d "pdfs" ]; then
            ls -la pdfs/
            echo "PDF count: $(ls -1 pdfs/*.pdf 2>/dev/null | wc -l)"
          else
            echo "No pdfs directory found!"
          fi
          
          echo ""
          echo "Current directory contents:"
          ls -la

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lab-pdfs
          path: pdfs/
          if-no-files-found: warn
        if: always()
