# .github/workflows/convert-to-pdf.yml

name: Labs to HTML and PDF
# This workflow is triggered on pushes to the repository or manually.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /labs directory
    paths:
      - "labs/*/*.md"
      - "labs/*/images/**"
      - ".github/styles/**"
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      # Setup Pandoc using dedicated action (much faster than apt-get)
      - name: Setup Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: 3.1.3

      # Install wkhtmltopdf and fonts
      - name: Install wkhtmltopdf and fonts
        run: |
          echo "Installing wkhtmltopdf..."
          
          # Use wget to download specific version (faster than apt)
          wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
          sudo apt-get install -y ./wkhtmltox_0.12.6.1-3.jammy_amd64.deb
          rm wkhtmltox_0.12.6.1-3.jammy_amd64.deb
          echo "✓ wkhtmltopdf installed"
          
          # Install fonts for emoji support
          sudo apt-get install -y --no-install-recommends fonts-noto-color-emoji || echo "Warning: Could not install emoji fonts"
          echo "✓ Emoji fonts installation attempted"

          # Verify installations
          pandoc --version
          wkhtmltopdf --version
        timeout-minutes: 5

      # Convert labs to HTML first (needed for PDF generation)
      - name: Convert labs to HTML
        run: |
          # Convert each README.md to HTML in its own directory
          for lab_dir in labs/*/; do
            if [ -d "$lab_dir" ] && [ -f "${lab_dir}README.md" ]; then
              lab_name=$(basename "$lab_dir")
              echo "Converting $lab_name to HTML..."
              
              # Change to the lab directory to ensure relative image paths work
              cd "$lab_dir"
              
              # Preprocess markdown for GitHub-style callouts and emoji preservation
              cp "README.md" "${lab_name}_processed.md"
              
              # Convert GitHub-style callouts to HTML divs with classes
              sed -i 's/> \[!NOTE\]/> <div class="note">**Note:** /g' "${lab_name}_processed.md"
              sed -i 's/> \[!TIP\]/> <div class="tip">**Tip:** /g' "${lab_name}_processed.md"
              sed -i 's/> \[!IMPORTANT\]/> <div class="warning">**Important:** /g' "${lab_name}_processed.md"
              sed -i 's/> \[!WARNING\]/> <div class="warning">**Warning:** /g' "${lab_name}_processed.md"
              sed -i 's/> \[!CAUTION\]/> <div class="warning">**Caution:** /g' "${lab_name}_processed.md"
              
              # Add closing div tags for callouts (simple approach - assumes single line callouts)
              sed -i 's/\(> <div class="[^"]*">.*\)$/\1<\/div>/g' "${lab_name}_processed.md"
              
              # CRITICAL: Remove emojis from headers FIRST, before Pandoc processes them
              # This ensures Pandoc generates consistent TOC links and header IDs
              echo "Removing emojis from headers in $lab_name BEFORE Pandoc processing..."
              sed -i 's/^## [^a-zA-Z0-9]*\([a-zA-Z].*\)$/## \1/g' "${lab_name}_processed.md"
              sed -i 's/^### [^a-zA-Z0-9]*\([a-zA-Z].*\)$/### \1/g' "${lab_name}_processed.md"
              sed -i 's/^#### [^a-zA-Z0-9]*\([a-zA-Z].*\)$/#### \1/g' "${lab_name}_processed.md"
              
              # Fix any manual anchor links to match cleaned headers
              # Remove emojis and leading dashes from anchor links
              sed -i 's|(#[^a-zA-Z0-9]*-*\([a-zA-Z][^)]*\))|(#\1)|g' "${lab_name}_processed.md"
              
              # Extract the first H1 title from the markdown file for use as page title
              lab_title=$(grep -m 1 '^# ' "${lab_name}_processed.md" | sed 's/^# //' | sed 's/[*_`]//g' | head -1)
              if [ -z "$lab_title" ]; then
                lab_title="$lab_name - Microsoft Copilot Studio Labs"
              fi
              echo "Using page title: $lab_title"
              
              # Convert to HTML with custom CSS (no TOC for individual pages)
              if pandoc "${lab_name}_processed.md" \
                -o "${lab_name}.html" \
                --standalone \
                --self-contained \
                --css="../../.github/styles/html.css" \
                --html-q-tags \
                --section-divs \
                --id-prefix="" \
                --metadata title="$lab_title" \
                -f markdown+auto_identifiers+gfm_auto_identifiers+emoji+header_attributes \
                -t html5 2>/dev/null; then
                echo "✓ Successfully converted $lab_name to HTML"
                
                # Remove the title block header (keep <title> in <head>, remove <header> in body)
                # Use a more robust approach to remove the header block
                sed -i '/<header id="title-block-header">/,/<\/header>/d' "${lab_name}.html"
                
                # Post-process HTML to fix anchor links and remove problematic IDs
                # Remove empty or invalid IDs that might break navigation
                sed -i 's/id=""//g' "${lab_name}.html"
                sed -i 's/id="[[:space:]]*"//g' "${lab_name}.html"
                
                # Ensure proper anchor link format in HTML
                # Fix links that might have been broken during conversion
                sed -i 's/href="#[[:space:]]*\([^"[:space:]]*\)[[:space:]]*"/href="#\1"/g' "${lab_name}.html"
                
                # Add name attributes to headers for better anchor compatibility
                # This ensures that both id="section" and name="section" work for navigation
                sed -i 's/<h\([1-6]\) id="\([^"]*\)"/<h\1 id="\2" name="\2"/g' "${lab_name}.html"
                
                # Also add standalone anchor tags before headers as backup
                sed -i 's/<h\([1-6]\) id="\([^"]*\)" name="\([^"]*\)"/<a name="\2"><\/a><h\1 id="\2" name="\3"/g' "${lab_name}.html"
                
                # Make external links open in new window
                # Add target="_blank" and rel="noopener noreferrer" to external links (http/https)
                # This regex matches links that start with http:// or https:// and adds the attributes
                sed -i 's/<a href="\(https\?:\/\/[^"]*\)"/<a href="\1" target="_blank" rel="noopener noreferrer"/g' "${lab_name}.html"
                
                # Add simple favicon for consistent branding (blue circle with L)
                sed -i 's|</head>|  <link rel="icon" href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj4KICA8Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI0NSIgZmlsbD0iIzJCNTc5QSIvPgogIDx0ZXh0IHg9IjUwIiB5PSI2NSIgZm9udC1mYW1pbHk9IkFyaWFsLHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iNDUiIGZvbnQtd2VpZ2h0PSJib2xkIiBmaWxsPSJ3aGl0ZSIgdGV4dC1hbmNob3I9Im1pZGRsZSI+TDwvdGV4dD4KPC9zdmc+">\n</head>|' "${lab_name}.html"
                
                echo "✓ Successfully converted $lab_name to HTML with favicon"
              else
                # Try fallback conversion without CSS
                echo "Trying fallback HTML method for $lab_name..."
                if pandoc "${lab_name}_processed.md" -o "${lab_name}.html" \
                  --standalone \
                  --section-divs \
                  --toc \
                  --id-prefix="" \
                  --metadata title="$lab_title" \
                  -f markdown+auto_identifiers+gfm_auto_identifiers+emoji \
                  -t html5 2>/dev/null; then
                  echo "✓ Fallback HTML conversion succeeded for $lab_name"
                  
                  # Remove the title block header for fallback conversion too
                  sed -i '/<header id="title-block-header">/,/<\/header>/d' "${lab_name}.html"
                fi
              fi
              
              # Cleanup processed file
              rm -f "${lab_name}_processed.md"
              
              # Change back to root directory
              cd - > /dev/null
            fi
          done

          echo "Generated HTML count: $(find labs -name "*.html" -type f | wc -l)"

      # Convert HTML to PDF (preserves hyperlinks better)
      - name: Convert HTML to PDF
        run: |
          # Convert each HTML file to PDF in its own directory
          for lab_dir in labs/*/; do
            if [ -d "$lab_dir" ]; then
              lab_name=$(basename "$lab_dir")
              html_file="${lab_dir}${lab_name}.html"
              
              if [ -f "$html_file" ]; then
                echo "Converting $lab_name HTML to PDF..."
                
                # Change to the lab directory
                cd "$lab_dir"
                
                # Debug: Check HTML file before PDF conversion
                echo "Checking HTML structure for $lab_name:"
                
                # Check if title-block-header still exists (should be removed)
                if grep -q "title-block-header" "${lab_name}.html"; then
                  echo "⚠️  WARNING: title-block-header still found in HTML before PDF conversion"
                  echo "Attempting to remove it now..."
                  sed -i '/<header id="title-block-header">/,/<\/header>/d' "${lab_name}.html"
                else
                  echo "✓ No title-block-header found in HTML - clean for PDF conversion"
                fi
                
                # Optimize HTML for PDF bookmarks - ensure headers have proper structure
                echo "Optimizing HTML for PDF bookmarks..."
                
                # Ensure all headers have both id and name attributes for better PDF navigation
                sed -i 's/<h\([1-6]\) id="\([^"]*\)"[^>]*>/<h\1 id="\2" name="\2">/g' "${lab_name}.html"
                
                # Add anchor targets before headers for better PDF internal linking
                sed -i 's/<h\([1-6]\) id="\([^"]*\)" name="\([^"]*\)">/<a id="\2" name="\2"><\/a><h\1 id="\2" name="\3">/g' "${lab_name}.html"
                
                # Create a PDF-specific version of the HTML with internal links removed
                echo "Creating PDF-optimized version without internal links..."
                cp "${lab_name}.html" "${lab_name}_pdf.html"
                
                # Debug: Show what internal links were found before removal
                internal_link_count=$(grep -o '<a href="#[^"]*"[^>]*>[^<]*</a>' "${lab_name}_pdf.html" | wc -l)
                if [ "$internal_link_count" -gt 0 ]; then
                  echo "Found $internal_link_count internal links to remove:"
                  grep -o '<a href="#[^"]*"[^>]*>[^<]*</a>' "${lab_name}_pdf.html" | head -3
                else
                  echo "No HTML internal links found"
                fi
                
                # Remove HTML internal anchor links but keep the text content
                # Pattern: <a href="#something">text</a> becomes just: text
                sed -i 's/<a href="#[^"]*"[^>]*>\([^<]*\)<\/a>/\1/g' "${lab_name}_pdf.html"
                
                # Remove any remaining anchor elements with internal links
                sed -i 's/<a[^>]*href="#[^"]*"[^>]*>//g' "${lab_name}_pdf.html"
                sed -i 's/<\/a>//g' "${lab_name}_pdf.html"
                
                # Remove markdown-style internal links that might still be in HTML
                # Pattern: [text](#section) becomes just: text
                sed -i 's/\[\([^]]*\)\](#[^)]*)/\1/g' "${lab_name}_pdf.html"
                
                # Remove any orphaned internal link references
                sed -i 's/(#[^)]*)//g' "${lab_name}_pdf.html"
                
                # Clean up any double spaces or formatting issues from link removal
                sed -i 's/  \+/ /g' "${lab_name}_pdf.html"
                
                echo "✓ Internal links removed from PDF version"
                
                echo "First few links in HTML:"
                grep -o '<a href="#[^"]*"[^>]*>[^<]*</a>' "${lab_name}.html" | head -3 || echo "No internal links found in HTML"
                
                # Convert HTML to PDF using wkhtmltopdf with proper TOC and bookmarks
                echo "Generating PDF with Table of Contents and bookmarks..."
                if wkhtmltopdf \
                  --page-size Letter \
                  --margin-top 0.75in \
                  --margin-bottom 0.75in \
                  --margin-left 0.75in \
                  --margin-right 0.75in \
                  --enable-local-file-access \
                  --enable-internal-links \
                  --enable-external-links \
                  --outline \
                  --outline-depth 6 \
                  --print-media-type \
                  --no-stop-slow-scripts \
                  --javascript-delay 2000 \
                  --encoding utf-8 \
                  --disable-smart-shrinking \
                  --enable-toc-back-links \
                  --footer-right "Page [page] of [topage]" \
                  --footer-font-size 10 \
                  --footer-spacing 5 \
                  --title "$lab_title" \
                  --dump-outline "${lab_name}_outline.xml" \
                  toc \
                  --toc-header-text "Table of Contents" \
                  --toc-level-indentation 15 \
                  --toc-text-size-shrink 0.8 \
                  "${lab_name}_pdf.html" \
                  "${lab_name}.pdf" 2>/dev/null; then
                  echo "✓ Successfully converted $lab_name HTML to PDF with TOC and bookmarks"
                  
                  # Check if outline was generated
                  if [ -f "${lab_name}_outline.xml" ]; then
                    echo "PDF outline/bookmarks created:"
                    head -10 "${lab_name}_outline.xml" || echo "Could not read outline file"
                    rm -f "${lab_name}_outline.xml"  # Clean up
                  fi
                else
                  echo "✗ Failed to convert $lab_name HTML to PDF"
                  echo "Trying fallback PDF conversion without TOC..."
                  
                  # Fallback without TOC
                  if wkhtmltopdf \
                    --page-size Letter \
                    --margin-top 0.75in \
                    --margin-bottom 0.75in \
                    --margin-left 0.75in \
                    --margin-right 0.75in \
                    --enable-local-file-access \
                    --enable-internal-links \
                    --outline \
                    --outline-depth 4 \
                    --encoding utf-8 \
                    --title "$lab_title" \
                    "${lab_name}_pdf.html" "${lab_name}.pdf" 2>/dev/null; then
                    echo "✓ Fallback PDF conversion succeeded for $lab_name"
                  else
                    echo "✗ Both PDF conversion methods failed for $lab_name"
                  fi
                fi
                
                # Cleanup temporary PDF-specific HTML file
                rm -f "${lab_name}_pdf.html"
                
                # Change back to root directory
                cd - > /dev/null
              else
                echo "✗ HTML file not found for $lab_name"
              fi
            fi
          done

          echo "Generated PDF count: $(find labs -name "*.pdf" -type f | wc -l)"

      # Commit PDFs and HTML files back to the repository
      - name: Commit PDFs and HTML files to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "Current git status:"
          git status

          echo ""
          echo "Checking for generated files to add:"
          echo "PDF files:"
          find labs -name "*.pdf" -type f
          echo "HTML files:"
          find labs -name "*.html" -type f

          # Sync with latest remote changes to avoid push conflicts during long runs
          git pull --rebase --autostash origin main

          # Add all generated files
          git add labs/

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No generated files to commit"
          else
            echo "Committing generated PDF and HTML files..."
            git commit -m "Auto-generated PDFs and HTML files for lab documentation [skip ci]"
            echo "Pushing changes..."
            git push
          fi
