# =============================================================================
# MICROSOFT COPILOT STUDIO LABS - WEB DEPLOYMENT WORKFLOW
# =============================================================================
# This workflow deploys generated HTML files to GitHub Pages, creating a
# professional web portal for accessing lab documentation with:
# - Homepage with lab directory and download links
# - Individual lab pages with styled content
# - Responsive design and professional branding
# =============================================================================

name: 🌐 Deploy Lab Portal to GitHub Pages

# =============================================================================
# WORKFLOW TRIGGERS
# =============================================================================
on:
  # Deploy when HTML files or styling changes
  push:
    branches: ["main"]
    paths:
      - "labs/**/*.html"         # Generated HTML files
      - ".github/styles/**"      # CSS styling updates
      - ".github/workflows/deploy-lab-portal.yml"  # This workflow file

  # Allow manual deployment from GitHub Actions UI
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force complete rebuild of site'
        required: false
        default: false
        type: boolean

# =============================================================================
# GITHUB PAGES PERMISSIONS
# =============================================================================
# Required permissions for deploying to GitHub Pages
permissions:
  contents: read    # Read repository content
  pages: write      # Deploy to GitHub Pages
  id-token: write   # GitHub Pages deployment token

# =============================================================================
# DEPLOYMENT CONCURRENCY CONTROL
# =============================================================================
# Ensure only one deployment runs at a time, but don't cancel in-progress 
# deployments to avoid corrupted states
concurrency:
  group: "pages-deployment"
  cancel-in-progress: false

# =============================================================================
# WORKFLOW JOBS
# =============================================================================
jobs:
  # ---------------------------------------------------------------------------
  # JOB 1: BUILD GITHUB PAGES SITE
  # ---------------------------------------------------------------------------
  build-site:
    name: 🏗️ Build Lab Portal Site
    runs-on: ubuntu-latest
    
    steps:
      # =================================================================
      # STEP 1: REPOSITORY AND PAGES SETUP
      # =================================================================
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Configure GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create Pages site structure
        run: |
          # Create the site directory
          mkdir -p _site
          
          # Copy CSS files
          mkdir -p _site/styles
          cp -r .github/styles/* _site/styles/
          
          # Convert root README.md to HTML as the main page
          echo "Converting root README.md to homepage..."
          
          # Enhance README for web display
          cp README.md _site/README_processed.md
          
          # Update the table header to replace URL with Download column
          sed -i 's/| Title | URL | Overview |/| Title | Download | Overview |/g' _site/README_processed.md
          sed -i 's/|-------|-----|----------|/|-------|----------|----------|/g' _site/README_processed.md
          
          # Make the title clickable (links to HTML) and put PDF download in Download column
          # Process each lab row - pattern: | Title | [link-text](./labs/lab-name) | Overview |
          # Replace with: | [Title](labs/lab-name/lab-name.html) | [📋 PDF](labs/lab-name/lab-name.pdf) | Overview |
          sed -i -E 's/\| ([^|]+) \| \[([^]]+)\]\(\.\/labs\/([^/]+)\) \| ([^|]+) \|/| [\1](labs\/\3\/\3.html) | [📋 PDF](labs\/\3\/\3.pdf) | \4 |/g' _site/README_processed.md
          
          # Convert README to HTML with custom styling (using embedded resources to fix CSS path issue)
          pandoc _site/README_processed.md \
            -o _site/index.html \
            --standalone \
            --embed-resources \
            --css="styles/html.css" \
            --html-q-tags \
            --section-divs \
            --metadata title="Microsoft Copilot Studio Labs" \
            -f markdown+auto_identifiers+gfm_auto_identifiers+emoji \
            -t html5
          
          # Remove the title block header (keep <title> in <head>, remove <header> in body)
          # Use a more robust approach to remove the header block
          sed -i '/<header id="title-block-header">/,/<\/header>/d' _site/index.html
          
          # Add lab-table class and normalize column widths (use Perl for robust multi-line handling)
          perl -0pi -e 's/<table style="width:100%;">/<table class="lab-table" style="width:100%;">/' _site/index.html
          perl -0pi -e 's|<colgroup>.*?</colgroup>|<colgroup><col style="width: 25%" /><col style="width: 10%" /><col style="width: 65%" /></colgroup>|s' _site/index.html

          # Make external links open in new window on homepage
          # Add target="_blank" and rel="noopener noreferrer" to external links (http/https)
          sed -i 's/<a href="\(https\?:\/\/[^"]*\)"/<a href="\1" target="_blank" rel="noopener noreferrer"/g' _site/index.html

          # Add simple favicon to homepage (blue circle with L)
          sed -i 's|</head>|  <link rel="icon" href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj4KICA8Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI0NSIgZmlsbD0iIzJCNTc5QSIvPgogIDx0ZXh0IHg9IjUwIiB5PSI2NSIgZm9udC1mYW1pbHk9IkFyaWFsLHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iNDUiIGZvbnQtd2VpZ2h0PSJib2xkIiBmaWxsPSJ3aGl0ZSIgdGV4dC1hbmNob3I9Im1pZGRsZSI+TDwvdGV4dD4KPC9zdmc+">\n</head>|' _site/index.html
          
          # Copy all HTML files to the site
          for lab_dir in labs/*/; do
            if [ -d "$lab_dir" ]; then
              lab_name=$(basename "$lab_dir")
              html_file="${lab_dir}${lab_name}.html"
              pdf_file="${lab_dir}${lab_name}.pdf"
              
              if [ -f "$html_file" ]; then
                # Copy HTML file to site
                mkdir -p "_site/labs/$lab_name"
                cp "$html_file" "_site/labs/$lab_name/"
                
                # Copy PDF file if it exists
                if [ -f "$pdf_file" ]; then
                  cp "$pdf_file" "_site/labs/$lab_name/"
                fi
                
                # Copy images if they exist
                if [ -d "${lab_dir}images" ]; then
                  cp -r "${lab_dir}images" "_site/labs/$lab_name/"
                fi
                
                echo "✓ Copied lab: $lab_name"
              fi
            fi
          done
          
          # Clean up temp file
          rm -f _site/README_processed.md
          
          echo ""
          echo "📊 Site structure created:"
          find _site -type f | head -20
          echo "..."
          echo "Total files: $(find _site -type f | wc -l)"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # ---------------------------------------------------------------------------
  # JOB 2: DEPLOY TO GITHUB PAGES
  # ---------------------------------------------------------------------------
  deploy-site:
    name: 🚀 Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: 🌐 Deploy Lab Portal to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

# =============================================================================
# END OF WORKFLOW: Deploy Lab Portal to GitHub Pages
# =============================================================================
# This workflow successfully:
# ✅ Creates a professional homepage with lab directory and downloads
# ✅ Deploys all lab HTML files with consistent styling and navigation
# ✅ Provides responsive design optimized for web viewing
# ✅ Maintains proper linking between homepage and individual labs
# ✅ Serves the complete lab portal at GitHub Pages URL
# =============================================================================